### ISSUE TITLE
Error visualizing off-target sites

### ISSUE THREAD

**Issue by Dharmendra-G-1** [tsailabSJ/circleseq#37]
Hello, 
I am getting the following error on the visualization.py script, can you please advice, what may be the reason for this following error:

I clone the repository by running git clone --recursive https://github.com/tsailabSJ/circleseq.git
Install circleseq dependencies by entering the circleseq directory and running pip install -r requirements.txt

modified the .yaml file:
__________
reference_genome: /drive_2t/circleseq/hg19.fa
analysis_folder: /drive_2t/circleseq/output_test_site_2_lib28

bwa: /drive_2t/circleseq/bwa-0.7.11/bwa
samtools: /drive_2t/circleseq/samtools-1.3/samtools

read_threshold: 4
window_size: 3
mapq_threshold: 50
start_threshold: 1
gap_threshold: 3
mismatch_threshold: 6
merged_analysis: True

samples:
    HEK293_042-lib28_site_2:
        target: GAACACAAAGCATAGACTGCNGG
        read1: /drive_2t/circleseq/exp_25_fastq/test_withCas9_R1_001.trimmed_first_last_150.fastq
        read2: /drive_2t/circleseq/exp_25_fastq/test_withCas9_R2_001.trimmed_first_last_150.fastq
        controlread1: /drive_2t/circleseq/exp_25_fastq/test_withoutCas9_R1_001.trimmed_first_last_150.fastq
        controlread2: /drive_2t/circleseq/exp_25_fastq/test_withoutCas9_R2_001.trimmed_first_last_150.fastq
        description: HEK293_site_2
____________

Complete error message as follows:

[08/25 04:01:47PM][INFO][circleseq] Loading manifest...
[08/25 04:01:47PM][INFO][circleseq] Merging reads...
[08/25 04:01:48PM][INFO][alignReads] BWA genome index found.
[08/25 04:01:48PM][INFO][alignReads] Running paired end mapping for HEK293_042-lib28_site_2
[08/25 04:01:48PM][INFO][alignReads] /drive_2t/circleseq/bwa-0.7.11/bwa mem /drive_2t/circleseq/hg19.fa /drive_2t/circleseq/output_test_site_2_lib28/fastq/HEK293_042-lib28_site_2_merged.fastq.gz  > /drive_2t/circleseq/output_test_site_2_lib28/aligned/HEK293_042-lib28_site_2.sam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 290 sequences (85206 bp)...
[M::mem_process_seqs] Processed 290 reads in 0.220 CPU sec, 0.223 real sec
[main] Version: 0.7.11-r1034
[main] CMD: /drive_2t/circleseq/bwa-0.7.11/bwa mem /drive_2t/circleseq/hg19.fa /drive_2t/circleseq/output_test_site_2_lib28/fastq/HEK293_042-lib28_site_2_merged.fastq.gz
[main] Real time: 3.291 sec; CPU: 3.280 sec
[08/25 04:01:51PM][INFO][alignReads] Paired end mapping for HEK293_042-lib28_site_2 completed.
[08/25 04:01:51PM][INFO][alignReads] /drive_2t/circleseq/samtools-1.3/samtools sort -o /drive_2t/circleseq/output_test_site_2_lib28/aligned/HEK293_042-lib28_site_2.bam /drive_2t/circleseq/output_test_site_2_lib28/aligned/HEK293_042-lib28_site_2.sam
[08/25 04:01:51PM][INFO][alignReads] Sorting by coordinate position for HEK293_042-lib28_site_2 complete.
[08/25 04:01:51PM][INFO][alignReads] /drive_2t/circleseq/samtools-1.3/samtools index /drive_2t/circleseq/output_test_site_2_lib28/aligned/HEK293_042-lib28_site_2.bam
[08/25 04:01:51PM][INFO][alignReads] Indexing for HEK293_042-lib28_site_2 complete.
[08/25 04:01:51PM][INFO][alignReads] /drive_2t/circleseq/samtools-1.3/samtools sort -o /drive_2t/circleseq/output_test_site_2_lib28/aligned/HEK293_042-lib28_site_2_sorted.bam -n /drive_2t/circleseq/output_test_site_2_lib28/aligned/HEK293_042-lib28_site_2.bam
[08/25 04:01:51PM][INFO][alignReads] Sorting for HEK293_042-lib28_site_2 by name complete.
[08/25 04:01:51PM][INFO][alignReads] BWA genome index found.
[08/25 04:01:51PM][INFO][alignReads] Running paired end mapping for control_HEK293_042-lib28_site_2
[08/25 04:01:51PM][INFO][alignReads] /drive_2t/circleseq/bwa-0.7.11/bwa mem /drive_2t/circleseq/hg19.fa /drive_2t/circleseq/output_test_site_2_lib28/fastq/control_HEK293_042-lib28_site_2_merged.fastq.gz  > /drive_2t/circleseq/output_test_site_2_lib28/aligned/control_HEK293_042-lib28_site_2.sam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 1854 sequences (542445 bp)...
[M::mem_process_seqs] Processed 1854 reads in 0.772 CPU sec, 0.777 real sec
[main] Version: 0.7.11-r1034
[main] CMD: /drive_2t/circleseq/bwa-0.7.11/bwa mem /drive_2t/circleseq/hg19.fa /drive_2t/circleseq/output_test_site_2_lib28/fastq/control_HEK293_042-lib28_site_2_merged.fastq.gz
[main] Real time: 3.803 sec; CPU: 3.788 sec
[08/25 04:01:55PM][INFO][alignReads] Paired end mapping for control_HEK293_042-lib28_site_2 completed.
[08/25 04:01:55PM][INFO][alignReads] /drive_2t/circleseq/samtools-1.3/samtools sort -o /drive_2t/circleseq/output_test_site_2_lib28/aligned/control_HEK293_042-lib28_site_2.bam /drive_2t/circleseq/output_test_site_2_lib28/aligned/control_HEK293_042-lib28_site_2.sam
[08/25 04:01:55PM][INFO][alignReads] Sorting by coordinate position for control_HEK293_042-lib28_site_2 complete.
[08/25 04:01:55PM][INFO][alignReads] /drive_2t/circleseq/samtools-1.3/samtools index /drive_2t/circleseq/output_test_site_2_lib28/aligned/control_HEK293_042-lib28_site_2.bam
[08/25 04:01:55PM][INFO][alignReads] Indexing for control_HEK293_042-lib28_site_2 complete.
[08/25 04:01:55PM][INFO][alignReads] /drive_2t/circleseq/samtools-1.3/samtools sort -o /drive_2t/circleseq/output_test_site_2_lib28/aligned/control_HEK293_042-lib28_site_2_sorted.bam -n /drive_2t/circleseq/output_test_site_2_lib28/aligned/control_HEK293_042-lib28_site_2.bam
[08/25 04:01:55PM][INFO][alignReads] Sorting for control_HEK293_042-lib28_site_2 by name complete.
[08/25 04:01:55PM][INFO][circleseq] Finished merging and aligning reads.
[08/25 04:01:55PM][INFO][circleseq] Identifying off-target cleavage sites.
[08/25 04:01:55PM][INFO][circleseq] Window: 3, MAPQ: 50, Gap: 3, Start 1, Mismatches 6, Search_Radius 20
Writing counts to /drive_2t/circleseq/output_test_site_2_lib28/identified/HEK293_042-lib28_site_2_count.txt
Tabulate nuclease merged start positions.
Tabulate control merged start positions.
Writing matched table
Writing unmatched table
[08/25 04:01:56PM][INFO][circleseq] Visualizing off-target sites
****[08/25 04:01:56PM][ERROR][circleseq] Error visualizing off-target sites.
[08/25 04:01:56PM][ERROR][circleseq] Traceback (most recent call last):
  File "/opt/circleseq/circleseq/circleseq.py", line 182, in visualize
    visualizeOfftargets(infile, outfile, title=sample)
  File "/opt/circleseq/circleseq/visualization.py", line 55, in visualizeOfftargets
    offtargets, target_seq, total_seq = parseSitesFile(infile)
  File "/opt/circleseq/circleseq/visualization.py", line 45, in parseSitesFile
    return offtargets, target_seq, total_seq
UnboundLocalError: local variable 'target_seq' referenced before assignment**

[2.0, 2.0] [4.0, 4.0]**

Thanks,

Dharm

**Comment by jmuribes** [comment]
Hi! I've been having the same error. I was wondering if there has been any updates with this issue.

Thanks,
José

**Comment by sdmiller93** [comment]
**The only time I had this error and was able to clear was when I realized I was using the incorrect target sequence.

**Comment by YuZhang337** [comment]
Hi! I've been having the same error. I was wondering if there has been any updates with this issue. and I change the target sequence from CAGTGATAATTTCTGGGTTAAGG to CAGTGATAATTTCTGGGTTANGG but got same error. 

Thanks,
Zhangyu

**Comment by wuyank** [comment]
I'm getting the same error, the reason seems to be that the file 'identified_matched.txt' in folder 'identified' is empty.

**Comment by sm527** [comment]
Hi! Did anyone manage to solve this error? 

The only thing that allowed me to finish "analysis" was to completely delete line " read_threshold: 4"  from the manifest file, however, I only get a couple of off-target sites with only a few counts (up to 20 / not like 200-1000 in comparison to original published article).

Thanks,
Špela
